version: "3.4"
services:

  api:
    build:
      context: ./api
      dockerfile: DevDockerfile
    environment:
      - ENV=DEV
      - PORT=5000
      - GO111MODULE=on
    # env_file: ./docker/api/.env
    ports:
      - "5000:5000"
    volumes: 
      - ./api:/go/src/server
    tty: true
    depends_on:
      - db

  db:
    build:
      context: ./mysql
    restart: always
    environment:
      MYSQL_DATABASE: sample_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
    - ./mysql/sql:/docker-entrypoint-initdb.d
    - ./mysql/data:/var/lib/mysql
    - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./mysql/logs:/logs
    security_opt: # https://github.com/docker-library/mysql/issues/422
    - seccomp:unconfined
  
  frontend:
    build:
      dockerfile: DevDockerfile
      context: ./frontend
      target: dev
    tty: true
    ports:
      - "80:8080"
    volumes:
      - ./frontend/dist:/frontend/dist
      - ./frontend/src:/frontend/src
