version: 2
jobs:
  eslint:
    docker:
      - image: circleci/node:8.11.3

    steps:
      - checkout
      - run:
          name: lint
          command: |
            mkdir -p /tmp/test-reports/eslint
            cd ./frontend
            npm install
            cd ./src
            npx eslint components/* --format junit --output-file /tmp/test-reports/eslint/results.xml
      - store_test_results:
          path: /tmp/test-reports

  build:
    docker:
      - image: circleci/golang:1.12.6

    steps:
      - checkout
      #- run: go get -v -t -d ./...
      - run: cd api && GO111MODULE=on go test -v

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - eslint
      - build