version: "3.4"
services:
  swagger-editor:
   image: swaggerapi/swagger-editor
   ports:
    - "8001:8080"

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8002:8080"
    volumes:
      - ./:/swagger
    environment: 
      SWAGGER_JSON: /swagger/api.yaml
